---
title: Maker Dot Space.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
pygments: true
name: MAKER.space
description: Maker and Hacker Space Resources
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: barryclark/jekyll-now
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: briankb
  stackoverflow: 
  youtube: 
disqus: 
google_analytics: UA-40021758-3
url: http://maker.space
baseurl: 
markdown: redcarpet
highlighter: pygments
permalink: "/:title/"
version: v1.1.0
sass:
  style: expanded
gems:
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
